import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import Provide from '@/components/Provider';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
   
    <html lang="en">
      <body className={inter.className}>
     <Provide >

      <Header/>
        {children}
      <Footer/>
      <ToastContainer />
      </Provide>
        
        </body>
    </html>
   
  )
}
